### ISSUE TITLE
missing documentation

### ISSUE THREAD

**Issue by jamuhl** [gunjam/marko-i18next#1]
Would be great if you at least add some readme.md with an introduction and some basic sample how to use this module.

Do you still maintain this repo?

**Comment by gunjam** [comment]
Hello, I just got into the office so I wrote a quick readme, hopefully it helps!

**Comment by gunjam** [comment]
Also I'm currently using this taglib in all my projects so it is being maintained.

**Comment by jamuhl** [comment]
that's awesome...thanks a lot...

**Comment by jamuhl** [comment]
just made a tweet: https://twitter.com/jamuhl/status/899593760211959808

awesome job and addition to i18next
